<?php
/**
 * @category    Ewall
 * @package     Ewall_FilterExpandCollapse
 * @copyright   Copyright (c) http://www.ewalldev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/* @var $this Mage_Core_Block_Template */
/* @var $helper Ewall_FilterExpandCollapse_Helper_Data */ $helper = Mage::helper(strtolower('Ewall_FilterExpandCollapse'));
?>
<?php if ($helper->isCollapseable($this->getLayer(), $this->getFilter()->getFilterOptions())) : ?>
    <div class="m-filter-expand-collapse">
        <div class="btn-expand-collapse"></div>
    </div>
<?php endif; ?>
