<?php $homeid = Mage::getSingleton('cms/page')->getIdentifier() ?>
<?php if ($homeid != "home"): ?>
<?php $_menu = $this->renderCategoriesMenuHtml(0,'level-top') ?>
<?php if($_menu): ?>

<script type="text/javascript">


jQuery(document).ready(function() {
          jQuery('.toggle').click(function() {
               if (jQuery('.submenu').is(":hidden"))
               {
                    jQuery('.submenu').slideDown("fast");
               } else {
                    jQuery('.submenu').slideUp("fast");
               }
               return false;
          });
		  
		  /*Phone Menu*/

	jQuery(".topnav").accordion({
		accordion:false,
		speed: 300,
		closedSign: '[+]',
		openedSign: '[-]'

});
});


</script>
<div id="menu" class="hidden-desktop">
<div class="container">
  <ul class="navmenu">
    <li>
      <div class="menutop clearfix">
        <h2>Categories</h2>
        <a class="toggle"><span></span></a>
      </div>
      <ul class="submenu" style="display:none;">
        <li>
          <ul class="topnav">
            <?php echo $_menu ?>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
  </div>
</div>

<?php endif ?>
<?php endif?>