<?php 
/**
 * @category    Ewall
 * @package     Ewall_FilterShowMore
 * @copyright   Copyright (c) http://www.ewalldev.com
 * @license     http://www.ewalldev.com/license  Proprietary License
 */
/** 
 * Template for showing Show More / Show less actions 
 * @author Ewall Team
 * Injected in designated place in filter items template used. In default template, designated place is right 
 * under list of items
 */
/* @var $block Ewall_Filters_Block_Filter */
?>
<?php /* @var $_helper Ewall_FilterShowMore_Helper_Data */ $_helper = Mage::helper(strtolower('Ewall_FilterShowMore'));?>
<?php /* @var $_core Ewall_Core_Helper_Data */ $_core = Mage::helper(strtolower('Ewall_Core'));?>
<?php /* @var $_filter Ewall_Filters_Model_Filter_Attribute */ $_filter = $block->getFilter();?>
<?php if ($_filter->getMIsShowMoreApplied() && !$_helper->isMethodDisabled($block, $_filter)) : ?>
<?php $method = $_helper->getMethod($block, $_filter) ?>
<div class="m-more-less" id="m-more-less-<?php echo Mage::helper('ewall_filters')->getFilterName($block, $_filter) ?>">
    <?php if ($method == 'scrollbar') : ?>
    <script type="text/javascript">(function ($) {
        $(document).trigger('m-filter-scroll-reset', [
            '<?php echo Mage::helper('ewall_filters')->getFilterName($block, $_filter) ?>',
            <?php echo $_filter->getFilterOptions()->getShowMoreItemCount() ?>
        ]);
    })(jQuery);</script>
    <?php elseif ($method == 'popup') : ?>
    <a href="#" class="m-show-more-popup-action"><?php echo $block->__('Show More') ?></a>
    <script type="text/javascript">(function ($) {
        $(document).trigger('m-show-more-popup-reset', [
            '<?php echo Mage::helper('ewall_filters')->getFilterName($block, $_filter) ?>',
            '<?php echo Mage::helper('ewall_core')->base64EncodeUrl($_helper->getPopupUrl($_filter)) ?>',
            '<?php echo Mage::helper('ewall_core')->base64EncodeUrl($_helper->getPopupTargetUrl($_filter)) ?>',
            '<?php echo $block->getSelectedSeoValues() ?>',
            '<?php echo Mage::getStoreConfig('ewall_filters/show_more_popup/action') ?>',
            <?php echo Mage::getStoreConfigFlag('ewall_filters/show_more_popup/progress') ? 'true' : 'false' ?>,
            <?php echo Mage::getStoreConfigFlag('ewall_filters/show_more_popup/debug') ? 'true' : 'false' ?>
        ]);
    })(jQuery);</script>
    <?php else : ?>
    <a class="m-show-less-action" href="#"><?php echo $block->__('Show Less') ?></a>
    <a class="m-show-more-action" href="#"><?php echo $block->__('Show More') ?></a>
    <script type="text/javascript">(function($) {
        $(document).trigger('m-show-more-reset', [
            '<?php echo Mage::helper('ewall_filters')->getFilterName($block, $_filter) ?>',
            <?php echo $_filter->getFilterOptions()->getShowMoreItemCount() ?>,
            <?php echo $_helper->isShowAllRequested($_filter) ? 'true' : 'false' ?>,
            <?php echo Mage::getStoreConfig('ewall_filters/display/show_more_time') ?>
        ]);
    })(jQuery);</script>
    <?php endif; ?>
</div>
<?php endif; ?>

