<?php 
/**
 * @category    Ewall
 * @package     Ewall_FilterColors
 * @copyright   Copyright (c) http://www.ewalldev.com
 * @license     http://www.ewalldev.com/license  Proprietary License
 */
/** 
 * Template for showing options for filter as a list of color boxes 
 * @author Ewall Team
 * Injected instead of standard catalog/layer/filter.phtml in Ewall_Filters_Block_Filter_Attribute init() method.
 */
/* @var $this Ewall_Filters_Block_Filter_Attribute */
?>
<div class="m-filter-colors horizontal <?php echo $this->getFilterClass() ?> <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
<?php foreach ($this->getItems() as $_item): ?>
	
	<a href="#" onclick="jQuery(this).find('div').<?php echo $_item->getMShowSelected() ? 'removeClass' : 'addClass' ?>('selected'); setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>'); return false;">
		<div class="m-color <?php if ($_item->getMShowSelected()): ?>selected<?php endif; ?> <?php echo $this->getFilterValueClass($_item) ?>"
			title="<?php echo $this->escapeHtml($_item->getLabel()) ?><?php if (Mage::getStoreConfigFlag('ewall_filters/display/count')) : ?> (<?php echo $_item->getCount() ?>)<?php endif; ?>">
			<div class="m-layer1"></div>
		</div>
	</a>
<?php endforeach ?>
</div>
