<?php
/**
 * @category    Ewall
 * @package     Ewall_FilterColors
 * @copyright   Copyright (c) http://www.ewalldev.com
 * @license     http://www.ewalldev.com/license  Proprietary License
 */
/**
 * Template for showing options for filter as a list of color boxes
 * @author Ewall Team
 * Injected instead of standard catalog/layer/filter.phtml in Ewall_Filters_Block_Filter_Attribute init() method.
 */
/* @var $this Ewall_Filters_Block_Filter_Attribute */
?>
<ol class="m-filter-colors labels <?php echo $this->getFilterClass() ?> <?php echo $this->getFilterOptions()->getIsReverse() ? 'm-reverse' : '' ?>">
    <?php foreach ($this->getItems() as $_item): ?>

    <li <?php if ($_item->getMShowSelected()): ?>class="m-selected-ln-item"<?php endif; ?>>
    <a href="#"
       onclick="jQuery(this).find('div').<?php echo $_item->getMShowSelected() ? 'removeClass' : 'addClass' ?>('selected'); setLocation('<?php echo $this->urlEscape($_item->getMSelected() ? $_item->getRemoveUrl() : $_item->getUrl()) ?>'); return false;">
        <div class="m-color <?php if ($_item->getMShowSelected()): ?>selected<?php endif; ?> <?php echo $this->getFilterValueClass($_item) ?>"
             title="<?php echo $this->escapeHtml($_item->getLabel()) ?> (<?php echo $_item->getCount() ?>)">
            <div class="m-layer1"></div>
        </div>
        <?php echo $this->escapeHtml($_item->getLabel()) ?>
    </a>
    <?php if (Mage::getStoreConfigFlag('ewall_filters/display/count')) : ?>
        (<?php echo $_item->getCount() ?>)
    <?php endif; ?>
    </li>
    <?php endforeach ?>
</ol>
<?php echo Mage::helper('ewall_core')->getNamedHtml('ewall_filters/markup', 'after_items', array('block' => $this)) ?>
